server:
  port: 8080


spring:
  application:
    name: project
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
    redis:
      host: localhost
      port: 6379

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: sa123456

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 3MB


# Đường dẫn để chứa file hình sản phẩm gửi lên
upload:
  path: C:\Users\MINH\Desktop\images
